name: CLI Tests with Flask Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          chmod +x ./tests/tests.sh
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          PIP_EXTRA_INDEX_URL="https://test.pypi.org/simple/" python3 -m pip install -e .

      - name: Install Bats
        run: |
          BATS_INSTALL_DIR="$HOME/.local"
          mkdir -p "$BATS_INSTALL_DIR"

          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          ./install.sh "$BATS_INSTALL_DIR"
          cd ..
          rm -rf bats-core
          echo "$BATS_INSTALL_DIR/bin" >> "$GITHUB_PATH"

      - name: Start Flask server and run bash tests
        run: |
          python3 -m tests & disown
          sleep 5
          bats tests/tests.sh
